import './globals.css'
import {Rajdhani } from 'next/font/google'

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['500'],
 })

export const metadata = {
  title: 'Cyberpunk Red Rules',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={rajdhani.className}>{children}</body>
    </html>
  )
}
