import './globals.css'
import './glitch_text.css'
import './glitch_btn.css'
import { Ubuntu } from 'next/font/google'

const ubuntu = Ubuntu ({
  subsets: ['latin'],
  weight: ['400', '500', '700']
 })

export const metadata = {
  title: 'Cyberpunk Red Rules',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={ubuntu.className}>{children}</body>
    </html>
  )
}
